### ISSUE TITLE
内置插件支持关闭

### ISSUE THREAD

**Issue by imsobear** [ice-lab/icejs#10]
build.json

```json
{
  "store": false
}
```

**Comment by chenbin92** [comment]
## 方案实现

> 将现有 plugins 数组的参数形式改成 fn

1. 在 build-scripts 提供 getBuiltInPlugins 方法
```ts
class Context {
  constructor({ command, rootDir = process.cwd(), args = {}, getBuiltInPlugins = () => {} }) {
     this.plugins = this.resolvePlugins(getBuiltInPlugins);
   }

  this.resolvePlugins = (getBuiltInPlugins) => {
    const builtInPlugins = getBuiltInPlugins(this.userConfig)
     ...
  }
}
```

2. 在 icejs 中透传插件
```ts
const getBuiltInPlugins = require('../lib/index');
 const devServer = await start({
      args: { ...rawArgv },
      // 将 现有的 plugins 改成接收一个 fn,
      getBuiltInPlugins
    });
```

3. 在 icejs 中配置插件时可过滤

```ts
const getBuiltInPlugins = (userConfig) => {

    const builtInPlugins = [
      'build-plugin-ice-core',
      'build-plugin-react-app',
      'build-plugin-ice-router',
      'build-plugin-ice-store',
      'build-plugin-ice-helpers',
      'build-plugin-ice-logger',
      'build-plugin-ice-config',
      'build-plugin-ice-request'
    ]

    return builtInPlugins.filter(plugin => {
        // 根据 userConfig 进行判断过滤掉对应的内置插件
   })
}
```

**Comment by imsobear** [comment]
那我理解就是下面这样：

```js
await build({
  args: { ...rawArgv },
  plugins: builtInPlugins,
});

// 改成
await build({
  args: { ...rawArgv },
  getBuiltInPlugins: (userConfig) => {
     return [];
  },
});
```

这个思路挺好的，唯一需要确认的就是执行顺序的问题，获取内置插件能不能放在获取 userConfig 后面，具体看下代码。

**Comment by chenbin92** [comment]
> 那我理解就是下面这样：
> 
> ```js
> await build({
>   args: { ...rawArgv },
>   plugins: builtInPlugins,
> });
> 
> // 改成
> await build({
>   args: { ...rawArgv },
>   getBuiltInPlugins: (userConfig) => {
>      return [];
>   },
> });
> ```
> 
> 这个思路挺好的，唯一需要确认的就是执行顺序的问题，获取内置插件能不能放在获取 userConfig 后面，具体看下代码。

1. 是的，就是上面的代码这样。
2. 在项目已经验证过，获取内置插件可以放在获取 userConfig 后面

**Comment by chenbin92** [comment]
> 那我理解就是下面这样：
> 
> ```js
> await build({
>   args: { ...rawArgv },
>   plugins: builtInPlugins,
> });
> 
> // 改成
> await build({
>   args: { ...rawArgv },
>   getBuiltInPlugins: (userConfig) => {
>      return [];
>   },
> });
> ```
> 
> 这个思路挺好的，唯一需要确认的就是执行顺序的问题，获取内置插件能不能放在获取 userConfig 后面，具体看下代码。

1. 你这个代码理解没问题。
2. 在业务项目已经验证过，获取内置插件可以放在获取 userConfig 后面

**Comment by imsobear** [comment]
顺序：

- build-scripts 支持 getBuiltInPlugins 并发版本
- icejs 从 plugins 切换到 getBuiltInPlugins 并发版本
- build-scripts 移除 plugins 并发版本
