### ISSUE TITLE
MPA 应用实践和文档优化

### ISSUE THREAD

**Issue by chenbin92** [ice-lab/icejs#104]
## 问题

1. 针对 MPA 应用文档没有提供 Layout 以及 Layout 用到的状态数据的说明
2. `examples/basic-mpa` 示例需要基于文档进行完善

## 方案 

推荐 Layout 跟着对应的页面，Layout 使用的数据定义在当前页面的 `models/*` 进行管理

```diff
  ├── src/
  │    ├── Dashboard/
  │    │   ├── models/        # 状态管理
+ │    |   ├── layout.js
  │    │   ├── app.js
  │    │   └── index.jsx
  │    └──  Home/
  │         ├── models/
+ │         ├── layout.js
  │         ├── app.js
  │         └── index.jsx
  ├── build.json
  ├── package.json
```

为什么 Layout 不是定义在 `src/layouts` 目录下，对应的数据维护在 `src/models` 下？

> 考虑不同的页面 layout 以及数据存在异同，会导致 models 数据打包了多余的问题

**Comment by ClarkXia** [comment]
感觉还是要考虑 Layout 复用的场景，通用 Layout 放 `src/layouts` 目录下应该也可以

**Comment by chenbin92** [comment]
> 感觉还是要考虑 Layout 复用的场景，通用 Layout 放 `src/layouts` 目录下应该也可以

1. 上面说了为什么作为默认推荐的方式
2. 如果是「通用的 layouts + 仅仅只有 layout 的数据」是没有问题的，但如果定义了额外的数据到 models 里的问题，考虑异同的数据的情况？

**Comment by ClarkXia** [comment]
第一点，Layout 比较特殊，大多数场景下很少有一个页面一个 layout 的场景，所以默认推荐方式直接跟着页面走是不是合适

第二点针对有数据交互的场景给出实践即可，如果 Layout 中需要有额外的同models 交互逻辑，可以增加一层 container ，比如：

```js
import BasicLayout from '@/layouts';
import { store as pageStore } from 'ice/About';

const PageLayout = (props) => {
    const [pageState, pageActions] = pageStore.useModel('default');
    return <BasicLayout {...props} {...pageState} />
}
export default PageLayout;
```

然后实际使用 PageLayout，其他通用场景继续使用 BasicLayout 即可

**Comment by chenbin92** [comment]
上述第二种数据交互是要 `src/models` 还是不要 `src/models`

**Comment by ClarkXia** [comment]
第二种数据交互是使用的 page 级别的 models

**Comment by chenbin92** [comment]
> 第一点，Layout 比较特殊，大多数场景下很少有一个页面一个 layout 的场景，所以默认推荐方式直接跟着页面走是不是合适
> 
> 第二点针对有数据交互的场景给出实践即可，如果 Layout 中需要有额外的同models 交互逻辑，可以增加一层 container ，比如：
> 
> ```js
> import BasicLayout from '@/layouts';
> import { store as pageStore } from 'ice/About';
> 
> const PageLayout = (props) => {
>     const [pageState, pageActions] = pageStore.useModel('default');
>     return <BasicLayout {...props} {...pageState} />
> }
> export default PageLayout;
> ```
> 
> 然后实际使用 PageLayout，其他通用场景继续使用 BasicLayout 即可

> 第二种数据交互是使用的 page 级别的 models

PageLayout 在页面的的外层，也就是 PageLayout 不在 Provider 里面，是拿不到 pageStore 的，你上面的写法应该会报错，上面的代码需要在 mpa 下把 Provider 包在 Layout 上

**Comment by ClarkXia** [comment]
> PageLayout 在页面的的外层，也就是 PageLayout 不在 Provider 里面，是拿不到 pageStore 的，你上面的写法应该会报错，上面的代码需要在 mpa 下把 Provider 包在 Layout 上

pageLayout 直接在页面里面 import 我理解就是可以的，我觉得关键问题就是如果 layout 复用应该推荐哪种方式来组织，每个 page 目录下面都有一个 layout 文件，我觉得不合理

**Comment by ClarkXia** [comment]
结论：
1. 通用 layout 还是放在 src/layouts 目录
2. 如果 layout 中有状态管理需求，可以使用全局 model，在文档中透出需要注意事项
