### ISSUE TITLE
[RFC] 使用 Hooks 来实现组件的生命周期

### ISSUE THREAD

**Issue by alvinhui** [ice-lab/icejs#105]
## 需求背景

- 对于老的 Class Component 易于迁移；
- 对于习惯生命周期思维的用户容易理解以及实现的统一；
- 对于互转研发模式可对齐搭建 API。

## 提案

参考：

- [How do lifecycle methods correspond to Hooks?](https://reactjs.org/docs/hooks-faq.html#how-do-lifecycle-methods-correspond-to-hooks)
- [react-use: Lifecycles](https://github.com/streamich/react-use)

APIs: 

- useUpdate <=> componentDidUpdate
- useMount <=> componentDidMount
- useUnmount <=> componentWillUnmount
- useRender  <=> render (只针对互转场景，本质是一个立即执行的函数)

使用：

```js
import { useMount, useUnmount } from 'ice';
```

## 讨论点

是创建一个新插件（plugin-lifecycles?）来实现这些对应生命周期的 Hooks 还是实现到 plugin-core？

**Comment by imsobear** [comment]
#76 可以结合这个一起看下

**Comment by imsobear** [comment]
hooks 这块我觉得需要整体来看，需要给用户一个统一完备的方案，是否需要放到 `ice` 包里导出可以讨论下看看，因为可能会比较多。

**Comment by chenbin92** [comment]
具体方案详见：https://github.com/ice-lab/icejs/issues/202
