### ISSUE TITLE
非路由文件中 lazy 加载组件方式

### ISSUE THREAD

**Issue by ClarkXia** [ice-lab/icejs#108]
### 问题

如果存在非路由文件中有使用 lazy 按需加载组件的需求，需要按 React.lazy 的方式加载不能直接使用 ice 中导出的 lazy 方法

### 预期结果

使用 lazy 加载组件的方式需要保持一致

**Comment by raohuiyong** [comment]
在routes.ts中使用React.lazy申明的component最终会被转化为icejs内置的lazy的模式，但是这种模式是无法直接当成组件使用的

``` javascript
#第一步， 在routes.ts中申明并暴露一个NotFound，并且在routerConfig中添加component
import React from 'react'
export const NotFound= React.lazy(() => import('@/pages/NotFound'));
const routerConfig =[{
path: '/404',
component: NotFound
}]
export default routerConfig;

# 第二步，在随意一个页面组件中引入routerConfig和NotFound，然后比较结果
import routerConfig, { NotFound} from '@/routes';
function Home(){
const Notcomponent =  routerConfig[0]['component'];
   console.log('routerConfig中/404地址的component', Notcomponent  );
  console.log('NotFound的component', NotFound);

const cmpt = routerConfig[1]
return (<div>
<NotFound /> /* 可以使用 */
<Notcomponent /> /* 使用报错 */
</div>
)

}
export default Home;
```
![微信截图_20200330135447](https://user-images.githubusercontent.com/26049430/77879918-0c916880-728e-11ea-8b23-e2406cf1ece0.png)


通过上面的图片进行NotFound的比较，发现直接引用NotFound和引用routerConfig之后的component明显发生了变化，直接引用NotFound是可以当成组件使用的，但是使用routerConfig中的component是无法当成组件使用

**Comment by ClarkXia** [comment]
## 方案
保证 `route` 文件中的使用和其他组件的用法一致，统一处理处理成从 ice 导出
通过 ast 方式修改 `route` 文件中使用逻辑,`lazy(() => import('@pages/Home'))` 转化成 `lazy(() => import('@pages/Home'), true)`

```js
function lazy(dynamicImport, isRouteComponent) {
  if (isRouteComponent) {
    return { dynamicImport, __lazy__: true };
  } else {
    return React.lazy(dynamicImport)
  }
}
```
