### ISSUE TITLE
调用 request API 时全局配置 baseURL 不生效

### ISSUE THREAD

**Issue by imsobear** [ice-lab/icejs#122]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

src/app.ts:

```js
import { createApp, IAppConfig } from 'ice';

const appConfig: IAppConfig = {
  request: {
    baseURL: 'http://127.0.0.1:8888',
  }
};

createApp(appConfig);
```

src/pages/Home/index.tsx:

```js

import React, { useEffect } from 'react';
import { useRequest, request } from 'ice';

// baseURL not work
request({
  url: '/api/reposxxxx',
});

function Home() {
  const { data, error, loading, request: fetchRepos } = useRequest({ url: '/api/getRepos' });

  // baseURL works
  request({
    url: '/api/repos',
  }

  useEffect(() => {
    (async function () {
      // baseURL works
      await fetchRepos();
    }());
  }, []);

  return (
    //...
  );
}

export default Home
```

* icejs version：latest
* Node verson：NAN
* Platform：NAN
* `build.json`：
* `src/app.(ts|js)`：

**What is the expected behavior?**

- request 的配置 createApp 时生效（其他插件的 module 一样），这个时机无法把控，因此代码文件里如果直接调用的话 createApp 还没生效。
- 看一下这个问题能不能解决，不能的话怎么避免

**Comment by imsobear** [comment]
同样的问题：

> 我这边开发的时候遇到一个情况就是ice的全局的APP_MODE ，import的之后不是立刻就能取到，经常是undefined，但是刷新页面刷新几次就能取到了

**Comment by imsobear** [comment]
before load 的逻辑 revert 掉了，这块的方案需要重新看下：

插件调整顺序之后的问题：

- SSR 下服务端渲染报错：regenerateRuntime 不存在
- src/app.ts 里 app.getInitialData 里 request 依然无法使用 appConfig.request.baseURL
- pages/Home/index.tsx 中的 page.getInitialProps 里 request 依然无法使用 appConfig.request.baseURL

因为 1 阻塞了相关测试，因此先 revert 掉了。

**Comment by chenbin92** [comment]
> before load 的逻辑 revert 掉了，这块的方案需要重新看下：
> 
> 插件调整顺序之后的问题：
> 
> * SSR 下服务端渲染报错：regenerateRuntime 不存在
> * src/app.ts 里 app.getInitialData 里 request 依然无法使用 appConfig.request.baseURL
> * pages/Home/index.tsx 中的 page.getInitialProps 里 request 依然无法使用 appConfig.request.baseURL
> 
> 因为 1 阻塞了相关测试，因此先 revert 掉了。

不是 before load 引起的，before load 只针对这个 issue 解决了 csr 渲染的问题，没有处理 ssr 时的情况， MR https://github.com/ice-lab/icejs/pull/188 兼容了 ssr 的情况
