### ISSUE TITLE
src 目录下没有 pages 目录，npm start 报错，无法启动

### ISSUE THREAD

**Issue by yeshengfei** [ice-lab/icejs#123]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
src 目录下没有 pages 目录，npm start 会报错:

```
ERR! CONFIG Failed to get config.
ERR! ENOENT: no such file or directory, scandir '/Users/xxx/xxx/src/pages'
```

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* icejs version：
1.0.16
* Node verson：
v10.15.1
* Platform：
mac os x
* `build.json`：
* `src/app.(ts|js)`：

**What is the expected behavior?**

项目可以被正常启动

**Comment by chenbin92** [comment]
@yeshengfei 已发布 ice.js@1.1.0 版本，更新即可
