### ISSUE TITLE
build.json 配置多 entry 无法生效

### ISSUE THREAD

**Issue by olvvlo** [ice-lab/icejs#133]
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* icejs version：v1.0.16
* Node verson：v12.14.0
* Platform：mac
* `build.json`：
```json
{
  "entry": {
    "index": "src/app.js",
    "portal": "src/portal/app.js"
  },
  "hash": true,
  "store": false,
  "plugins": [
    ["build-plugin-antd", {
      "themeConfig": {
        "primary-color": "#2679F4"
      }
    }],
    ["build-plugin-moment-locales", {
      "locales": ["zh-cn"]
    }]
  ]
}
```
* `src/app.(ts|js)`：
```js
createApp({
      app: {
        addProvider: ({ children }) => {
          return (
            <ConfigProvider locale={zhCN}>
              <UserContext.Provider value={user}>
                {children}
              </UserContext.Provider>
            </ConfigProvider>
          )
        }
      }
    })
```

`npm run build`

only `build/index.html`

**What is the expected behavior?**

`build/index.html` & `build/portal.html`

**Comment by chenbin92** [comment]
@Wiolem 已发布 ice.js@1.1.0 版本，更新即可
