### ISSUE TITLE
SSR 功能问题反馈

### ISSUE THREAD

**Issue by imsobear** [ice-lab/icejs#141]
## ~~P3: 在 `getInitialData/getInitialProps` 中调用 request 时 appConfig 没生效~~

老问题 #122 ，跟 SSR 无关，但 SSR 用到这个能力概率比较高

## ~~P3: getInitialData 和 getInitialProps 不能写相对地址~~

写了相对地址的话，服务端渲染时始终会去请求 `127.0.0.1:80/`，这块应该无解，需要在文档上说明下

## ~~Mock 能力失效~~

优先级 P0，faas 可能有一样的问题

## ~~start 时没有任何 debug 信息，页面一直在 loading~~

优先级 P1，输出必要的日志信息，同时看下多次请求的话前一次能不能取消掉，现在好像容易卡掉

## ~~P3: 偶现 `Error: HtmlWebpackPlugin: could not load file /Users/sobear/work/biz/ssr-t  est/public/favicon.png`~~

为什么有个 `sst-t  est`？

## ~~依赖 next 组件报错~~

优先级 P0

![image](https://user-images.githubusercontent.com/2505411/77252653-2e885b00-6c90-11ea-8be0-2a7e1eef167e.png)

## ~~改了 js 刷新页面 html 内容没更新~~

优先级 P0，之前反馈过貌似并没修复

## ~~P2: 脚手架默认代码里存在 window 使用问题导致服务端渲染报错~~

![image](https://user-images.githubusercontent.com/2505411/77385121-2fb9a500-6dc2-11ea-82be-de2372cf5691.png)

## ~~P2: server/index.js 代码没有 sourcemap，报错无法排查~~

![image](https://user-images.githubusercontent.com/2505411/77385169-54ae1800-6dc2-11ea-85ed-79a79a3cb909.png)

## P3: 一个 warning

![image](https://user-images.githubusercontent.com/2505411/77385193-62639d80-6dc2-11ea-8fa8-3866df147238.png)

**Comment by imsobear** [comment]
## ~~P0：第一次启动时报错~~

![image](https://user-images.githubusercontent.com/2505411/77387336-1ae01000-6dc8-11ea-9fca-0cca33d5ed9e.png)

**Comment by imsobear** [comment]
## P2: initialData 除了 initialStates，其他场景能不能直接用， 怎么用

**Comment by chenbin92** [comment]
未完成的已独立拆解 issue 进行跟进：

https://github.com/ice-lab/icejs/issues/170
https://github.com/ice-lab/icejs/issues/171
https://github.com/ice-lab/icejs/issues/168
