### ISSUE TITLE
路由切换后滚动条未置顶

### ISSUE THREAD

**Issue by raohuiyong** [ice-lab/icejs#149]
项目根据官网提供的案例Fusion Design Pro - TS进行测试，采用icejs配置式路由的方案
![1](https://user-images.githubusercontent.com/26049430/77385806-30ebd180-6dc4-11ea-8262-0d5ff031e0e8.png)
![2](https://user-images.githubusercontent.com/26049430/77385808-334e2b80-6dc4-11ea-81be-6a05a8cb70bb.png)
菜单切换后，右侧路由内容滚动条没有置顶，还保留到上次滚动位置。
``` javascript
// 采用官网手册页面滚动配置依然没有效果
Analysis.pageConfig = {
  scrollToTop: true
};
```

**Comment by chenbin92** [comment]
@raohuiyong 我试了下可以正常回到顶部，如下演示。

![demo](https://user-images.githubusercontent.com/3995814/77508721-505b2b00-6ea6-11ea-90a8-c0866f9f8b90.gif)

麻烦提供一个可复现的 demo：https://codesandbox.io/s/github/ice-lab/icejs/tree/master/examples/basic-spa

**Comment by raohuiyong** [comment]
@chenbin92  我试了下，如果使用默认的minHeight: '100vh'再配置pageConfig使用，可以实现切换路由后置顶的效果。但是为了实现菜单栏和导航栏固定的效果，只允许内容进行滚动,我修改成height: '100vh'后切换路由就无法置顶了
![微信截图_20200325165902](https://user-images.githubusercontent.com/26049430/77519150-f5333380-6eb9-11ea-9a4e-f5df4bfb63d1.png)

**Comment by chenbin92** [comment]
@raohuiyong 现在的是实现是 `window.scrollTo(0, 0);` 不支持你说的固定导航的情况，这块需要在看下

**Comment by chenbin92** [comment]
@raohuiyong 目前支持的是非 Fixed 的场景 scrollToTop，本质是调用的 `window.scroll(0, 0)`。详见 https://github.com/ReactTraining/react-router/issues/2019

**Comment by chenbin92** [comment]
## 需求

支持满屏高度即 `body: { height: '100vh' }` 场景下的路由切换时 scrollToTop

## 说明

按照 react-router 官方对 [scrollToTop](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/guides/scroll-restoration.md) 的文档指南，通常的做法有两种：
  * `window.scrollTo(0, 0);` 该实现能满足目前大部分需求，也是 icejs 中的实现，但是该实现在固定高度 100% 的情况下，路由区域的内容无法滚动到顶部
 * ScrollRestoration  & RestoredScroll 实现，该实现主要通过记录 `location.key` 和 `RestoredScroll` 组件来缓存滚动的位置并记录到 `sessionStorage`，然后当 `ScrollRestoration` 或者 `RestoredScroll ` 组件加载时，组件在 `sessionsStorage`中查找滚动条位置信息。社区关于 ScrollRestoration 的实现 [react-router-scroll-memory
](https://www.npmjs.com/package/react-router-scroll-memory)

## 方案

### 用户配置

```diff
import { createApp, IAppConfig } from 'ice';
const appConfig: IAppConfig = {
  router: {
+     scrollToTop: true  // 默认为 false
  },
};

createApp(appConfig);
```

* 权重：`appConfig.router.scrollToTop` > `pageConfig.scrollToTop`
* `appConfig.router.scrollToTop`：切换路由默认所有页面都将自动滚动到顶部，该配置适用于通用场景，且只需配置一次
* `pageConfig.scrollToTop`：切换路由时当前页面自动滚动到顶部，该配置只适用于当前页面，且页面高度大于 100% 的情况

###  icejs 实现
```diff
+ import ScrollMemory from 'react-router-scroll-memory';

export function Router(props: RouterProps) {
  return (
    <RouterComponent {...others}>
      <>
+      {appConfig.router. scrollToTop ? <ScrollMemory /> : null}
        <Routes routes={parsedRoutes} fallback={fallback}/>
      <>
    </RouterComponent>
  );
}
```

## 效果
![demo](https://user-images.githubusercontent.com/3995814/78006136-2c4c8d80-736f-11ea-8099-5f8cc56e2d4a.gif)

**Comment by chenbin92** [comment]
**结论：**

- icejs 只支持页面高度大于 100% 的场景，其本质是通过  `window.scrollTo(0, 0);` 实现，可在页面按需配置，如下：

```tsx
import * as React from 'react';

const HomePage = () = {

}

HomePage.pageConfig = {
   scrollTop: true
}
```

- 如果是满屏高度即 `body: { height: '100vh' }`  场景下的路由切换时 scrollToTop，需要自行实现，即找到当前需要滚动的 DOM 节点，然后绑定 [scrollTo](https://developer.mozilla.org/zh-CN/docs/Web/API/Element/scrollTo) 方法。

- 相关讨论和实现
  - https://github.com/ReactTraining/react-router/issues/2019
  - [Scroll Restoration](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/guides/scroll-restoration.md)
  - [react-router-scroll-top](https://www.npmjs.com/package/react-router-scroll-top)

**Comment by raohuiyong** [comment]
@chenbin92 可以在router中设置一个需要监听其滚动事件的元素，实现更加丰富的切换置顶效果。毕竟目前很多网站只是内容滚动，而头部和菜单栏是不需要滚动的

**Comment by chenbin92** [comment]
> @chenbin92 可以在router中设置一个需要监听其滚动事件的元素，实现更加丰富的切换置顶效果。毕竟目前很多网站只是内容滚动，而头部和菜单栏是不需要滚动的

@raohuiyong  可以考虑来个 PR 👏
