### ISSUE TITLE
build.json 配置多入口时，配置式路由无法为不同入口指定 routes.js

### ISSUE THREAD

**Issue by olvvlo** [ice-lab/icejs#159]
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

现在多入口 entry 都是默认取 src/routes.js

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* icejs version：
* Node verson：
* Platform：
* `build.json`：
* `src/app.(ts|js)`：

**What is the expected behavior?**

```js
"entry": {
    "index": "src/app.js",
    "portal": "src/portal/app.js"
  },
  "hash": true,
  "store": false,
  "router": {
     // 两个入口配置不同的 routes.js 地址 or 默认取 app.js 同级的 routes.js
     "index": { "configPath": "src/routes.js" },
     "portal": { "configPath": "src/portal/routes.js" }
  },
```

**Comment by ClarkXia** [comment]
这个架构更像是 mpa？

**Comment by iamwilllee** [comment]
老项目想迁移 icejs，一个大 SPA, 一个小SPA， 放到一个仓库了，之前用 ice-scripts 是定义了两个入口，不是 MPA 项目 #133 

> 这个架构更像是 mpa？

**Comment by imsobear** [comment]
@wiolem 可以直接钉钉里面聊下

**Comment by iamwilllee** [comment]
src/portal/app.js

```js
createApp({
      app: {
        addProvider: () => {
          // portal.html 不使用配置式路由 routes.js 可解决
          return (
            <UserContext.Provider value={user}>
              <ConfigProvider locale={zhCN}>
                {router()}
              </ConfigProvider>
            </UserContext.Provider>
          )
        }
      }
    })
```
