### ISSUE TITLE
可否配置 build.json 的 router 项为 false，不需要路由

### ISSUE THREAD

**Issue by olvvlo** [ice-lab/icejs#164]
**Do you want to request a *feature* or report a *bug*?**

*feature*

**What is the current behavior?**

现在配置式路由不配置 src/routes.js 直接报错

```
```

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* icejs version：
* Node verson：
* Platform：
* `build.json`：
* `src/app.(ts|js)`：

**What is the expected behavior?**

build.json

```js
{
  "hash": true,
  "store": false,
  "router": false
}
```

**Comment by chenbin92** [comment]
> 现在配置式路由不配置 src/routes.js 直接报错

什么叫配置式路由不配置 `src/routes.js` ?

路由规则：检测到 `src/routes.[ts|js]` 文件存在则是配置式路由，否则为约定式路由，详见文档：https://ice.work/docs/guide/basic/router
