### ISSUE TITLE
fallback未生效问题

### ISSUE THREAD

**Issue by raohuiyong** [ice-lab/icejs#166]
使用官方提供的模板Fusion Design Pro - TS进行测试，设置fallback属性后并未生效

1. 修改routes.ts文件，修改两个组件为按需加载模式
```
const Analysis = lazy(() => import('@/pages/Analysis'));
const Monitor = lazy(() => import('@/pages/Monitor'));
```

2. 修改app.tsx配置，添加router相关配置
```
const appConfig = {
  app: {
    rootId: 'ice-container',
    addProvider: ({ children }) => (
      <LocaleProvider locale={locale}>{children}</LocaleProvider>
    )
  },
  router: {
    type: 'browser',
    fallback: <div>我加载路由中...</div>
  }
};
```
运行项目后切换路由分析页面或监控页面并未显示“我加载路由中...”，而是显示“loading”
![微信截图_20200326155055](https://user-images.githubusercontent.com/26049430/77623095-7520d280-6f7a-11ea-9156-b8a4af305600.png)

**Comment by chenbin92** [comment]
如下演示将默认的 `loading...` 修改为 `加载中...`
代码演示： https://codesandbox.io/s/github/ice-lab/icejs/tree/release-next/examples/basic-spa

![demo](https://user-images.githubusercontent.com/3995814/77634968-c89c1c00-6f8c-11ea-8ee3-54165750f695.gif)

**Comment by raohuiyong** [comment]
@chenbin92 这种方式的确可以实现，但是在官方模板Fusion Design Pro - TS里面使用不生效 [项目演示](https://codesandbox.io/s/github/raohuiyong/fallbackDemo)

**Comment by chenbin92** [comment]
@raohuiyong 感谢反馈，已处理

**Comment by chenbin92** [comment]
@raohuiyong 已发布 icejs@1.1.4
