### ISSUE TITLE
脚手架默认代码里存在 window 使用问题导致服务端渲染报错

### ISSUE THREAD

**Issue by chenbin92** [ice-lab/icejs#168]
## 问题

![image](https://user-images.githubusercontent.com/3995814/77628715-60950800-6f83-11ea-87d5-fe2831e6bc25.png)

## 期望

模板默认兼容 ssr 的场景，判断 window 是否存在

**Comment by ClarkXia** [comment]
pro 模版中除了本身业务代码会有依赖 window 的逻辑之外，还有第三方依赖 比如 bizcharts 大量依赖 document 逻辑

**Comment by chenbin92** [comment]
已迁移至：https://github.com/alibaba/ice/issues/3178
