### ISSUE TITLE
build-plugin-fusion 在多主题时还存在一个问题，目前不知道怎么解决。

### ISSUE THREAD

**Issue by a188658587** [ice-lab/icejs#172]
['scss', 'scss-module'].forEach((rule) => {
      config.module
        .rule(rule)
        .use('ice-skin-loader')
        .loader(require.resolve('ice-skin-loader'))
        .options({
          themeFile,
          themeConfig: {...defaultScssVars, ...replaceVars, ...(themeVars || {}), nextPrefix },
        });
    });

单主题时replaceVars对象为空，defaultScssVars对象里是颜色值，在ui组建里面有用rgba（）的没有问题。
当在多主题时。replaceVars对象里对应的css变量的：var(--color-data1-3)，这个变量在rgba里面不起作用啊。所有用到rgba(var(--xxxxx),0.4)  的都不行。

这怎么解决呀？？还望大神指点迷津。

**Comment by ClarkXia** [comment]
用到的变量 比如 `--color-data1-3` 这个是否正确地被提取，例外用 `rgba(var(--color-data1-3),0.4)` 的地方也可以检查下具体样式解析成什么样子的

**Comment by a188658587** [comment]
我在使用 Dialog  弹窗组件时，
单主题会显示背景半透明遮罩，在浏览器上看样式值是：background-color: rgba(0,0,0,.2);
多主题就不显示遮罩。浏览器上看到的样式值是：background-color: rgba(var(--color-black),.2);

**Comment by ClarkXia** [comment]
--color-black 定义为 #000 的情况下应该是没问题的，可以提供复现 demo 重开 issue

**Comment by a188658587** [comment]
<img width="1194" alt="图片" src="https://user-images.githubusercontent.com/33589918/77984320-d44c6180-7343-11ea-8ba4-6baff57dc01b.png">

<img width="438" alt="图片" src="https://user-images.githubusercontent.com/33589918/77985108-17a7cf80-7346-11ea-823b-4decb1467e2c.png">

这样的rgba 没办法显示半透明呀。 是我设置不对吗？浏览器问题？

我猜测是这样。浏览器的rgba方法 只能解析四个参数rgba(0,0,0,.2) 这样的。
而rgba(#000, 0.2)这样的方式是sass 转成 rgba(0,0,0,.2)的。

但是rgba(var(--mask-background), 0.2)这样变量的方式 sass 没处理，就直接放出来了。导致浏览器也不认识。
