### ISSUE TITLE
start 时新增了 config.ts 未生效，需要重新启动

### ISSUE THREAD

**Issue by imsobear** [ice-lab/icejs#175]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

![image](https://user-images.githubusercontent.com/2505411/77718828-c97d8e00-701e-11ea-9564-7014f582162f.png)

重新 start 就生效了

**What is the expected behavior?**

立即生效

**Comment by ClarkXia** [comment]
验证了下新增和删除 config 文件均会在 `.ice` 目录下动态增删内容，ts 提示生效可能存在一定的延迟
