### ISSUE TITLE
是否能支持运行时扩展 APP_MODE

### ISSUE THREAD

**Issue by imsobear** [ice-lab/icejs#178]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

只能通过 `--mode` 参数指定 APP_MODE

**What is the expected behavior?**

某些场景下（比如内部发布），可能没办法在每个环境都构建一次，但是运行时的配置希望能够通过域名动态来区分，是否有可能动态设置 APP_MODE，比如：

```js
// src/app.ts
process.env.APP_MODE = /daily.a.com/.test(location.host) ? 'daily' : 'prod';

import { createApp } from 'ice';

createApp({...});
```

**Comment by ClarkXia** [comment]
运行时去扩展都会存在类似 request 碰到的问题，会因执行位置和时机的不同，导致不一样的配置

**Comment by imsobear** [comment]
顺便支持下服务端渲染时定义一个空的 global.window

**Comment by imsobear** [comment]
![image](https://user-images.githubusercontent.com/2505411/77771238-6bce5d80-7081-11ea-973e-65c1c8371866.png)

这个看下是不是也应该支持下，SSR+FaaS 的场景，`getInitalData` 必须写绝对路径，本地情况绝对路径可能会变，是不是注入进来更好？

**Comment by chenbin92** [comment]
目前已支持通过 `window.__app_mode__` 来支持运行时扩展，但是在 SSR 下会丢失 window 属性导致 `__app_mode__` 无法正常使用

**Comment by chenbin92** [comment]
已发布 icejs@1.1.4 版本
