### ISSUE TITLE
自定义工程配置收集

### ISSUE THREAD

**Issue by imsobear** [ice-lab/icejs#197]
> 针对需要修改 webpack 配置的场景整理一些常见 case

icejs 通过插件 `build-plugin-react-app` 提供核心的工程构建配置，如果需要修改这些配置，可以参考 [文档](https://ice.work/docs/guide/basic/build#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%85%8D%E7%BD%AE) ：

首先新建 `build.plugin.js` 文件作为一个自定义插件，然后写入以下代码：

```js
module.exports = ({ context, onGetWebpackConfig }) => {
  onGetWebpackConfig((config) => {
     // 常见需求怎么写参见 issue 回复
  });
}
```

最后在 `build.json` 里引入自定义插件即可：

```json
{
  "plugins": [
    "./build.plugin.js"
  ]
}
```

**Comment by imsobear** [comment]
## 修改 CSS Modules 规则

默认情况命名为 `*.module.scss` 的文件才会使用 CSS Modules，如果希望默认所有 scss 文件都是使用 CSS Modules：

```js
module.exports = ({ onGetWebpackConfig }) => {
  onGetWebpackConfig((config) => {
    config
      .module.rule('scss-module').test(/\.scss$/)
      .exclude.add(/node_modules/);
    config
      .module.rule('scss')
      .include.add(/node_modules/);
  });
};
```

**Comment by imsobear** [comment]
## 新增 webpack 插件

```js
const CircularDependencyPlugin = require('circular-dependency-plugin');

module.exports = ({ onGetWebpackConfig }) => {
  onGetWebpackConfig((config) => {
    config
      .plugin('CircularDependencyPlugin')
      .use(CircularDependencyPlugin, [{
         // 插件参数
      }]);
  });
};
```

**Comment by chenbin92** [comment]
- [friendly-errors-webpack-plugin](https://www.npmjs.com/package/friendly-errors-webpack-plugin)：友好的 webpack 错误展示插件
- [size-plugin](https://www.npmjs.com/package/size-plugin): 构建 size 大小对比和 gzipped 插件

**Comment by chenbin92** [comment]
已迁移至：https://github.com/alibaba/ice/issues/3179
