### ISSUE TITLE
hash 模式下 服务端渲染时路径匹配错误

### ISSUE THREAD

**Issue by imsobear** [ice-lab/icejs#199]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

匹配到错误的路由：

![image](https://user-images.githubusercontent.com/2505411/78025350-7728ce00-738c-11ea-8287-9c3f3be5daf1.png)

**What is the expected behavior?**

匹配到正确的路由。

**Comment by chenbin92** [comment]
在 faas-ssr 项目测试了下，看到控制台有如下错误输出。问题原因是在 SSR 渲染时服务端使用的是 StaticRouter，不能和 hashHistory 进行匹配。我理解在 SSR 场景下应该是不推荐使用 hashHistory 

- https://github.com/ReactTraining/react-router/issues/2111
- [matchPath 文档](https://github.com/ReactTraining/react-router/blob/78171da4fe0b410fc367d539d99d02156ecdb004/packages/react-router/do)


![image](https://user-images.githubusercontent.com/3995814/78737623-89a19980-7982-11ea-8008-350e21ab61dc.png)
