### ISSUE TITLE
页面级 store + lazy 使用报错

### ISSUE THREAD

**Issue by chenbin92** [ice-lab/icejs#201]
## 问题描述

路由里面 lazy import 进来的页面就会出现 model 加载的时候报 Component must be wrapped within a Provider 的问题

```diff
import { lazy } from 'ice';
import About from '@/pages/About';

export default [
  {
    path: '/',
    exact: true,
    // component: Home
+  component: lazy(() => import('@/pages/Home'))
  },
  {
    path: '/about',
    component: About
  }
];
```

## 预期行为
- model 支持 lazy

**Comment by imsobear** [comment]
另一个问题：

![image](https://user-images.githubusercontent.com/2505411/79180313-388b1d00-7e3c-11ea-9828-e51ef5980aae.png)
![image](https://user-images.githubusercontent.com/2505411/79180326-40e35800-7e3c-11ea-9097-48233615cdd1.png)
![image](https://user-images.githubusercontent.com/2505411/79180337-4476df00-7e3c-11ea-92c3-be3033401bab.png)

**Comment by chenbin92** [comment]
icejs@1.1.6 版本已修复
