### ISSUE TITLE
将 eslint 检测加入到构建过程中

### ISSUE THREAD

**Issue by imsobear** [ice-lab/icejs#219]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

lint 跟构建不相关

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* icejs version：
* Node verson：
* Platform：
* `build.json`：
* `src/app.(ts|js)`：

**What is the expected behavior?**

建议完整体验下 CRA，工程这块很多体验还是值得学习的。

该需求来自躺平的开发同学。

**Comment by imsobear** [comment]
js 语法错误控制台没有报：

CRA

![image](https://user-images.githubusercontent.com/2505411/79305812-a6ac0e80-7f26-11ea-975b-ffd72f69f940.png)

![image](https://user-images.githubusercontent.com/2505411/79305829-add31c80-7f26-11ea-9cd1-5c2268d2abd2.png)

icejs

终端表现正常，界面白屏，要在浏览器控制台才能看到错误

![image](https://user-images.githubusercontent.com/2505411/79305765-9136e480-7f26-11ea-8c26-da405691fc61.png)

**Comment by imsobear** [comment]
jsx 出错后优化：错误长、不准确、未在界面上展示

CRA

![image](https://user-images.githubusercontent.com/2505411/79305344-d0b10100-7f25-11ea-8620-ce9b6ba7a715.png)

![image](https://user-images.githubusercontent.com/2505411/79305691-72d0e900-7f26-11ea-974d-1c8589141139.png)

icejs

![image](https://user-images.githubusercontent.com/2505411/79305517-1f5e9b00-7f26-11ea-8738-aed52f9fef15.png)

**Comment by ClarkXia** [comment]
react-app-plugin 增加相关 feature：
1. 增加 react-error-overlay 的处理（ice-scripts 中支持，迁移过程中可能漏掉了）
2. 增加 eslint 前置检测，在 babel-loader 前检测，需通过 `eslintFormatter` 开启

**Comment by chenbin92** [comment]
已发布 icejs@1.2.0 版本支持
