### ISSUE TITLE
ice和react方式使用的lazy方法如何转换

### ISSUE THREAD

**Issue by raohuiyong** [ice-lab/icejs#231]
我有两个路由，分别使用ice和react的lazy方法引入，如何把lazy方法引入的component转化为React.lazy的component
![20200409124631](https://user-images.githubusercontent.com/26049430/78858862-343bba00-7a60-11ea-8f39-090481634371.png)

**Comment by chenbin92** [comment]
1. 在路由中推荐统一使用 `import { lazy } from 'ice'` ，在路由实现中会有相关逻辑的判断，最终也是转成了 React Lazy。**不要在路由文件中既使用 React Lazy 又使用 ice lazy**
2. 在非路由中也推荐使用 `import { lazy } from 'ice'`  保证编码风格的一致性

详见文档：[icejs - 代码分割](https://ice.work/docs/guide/advance/code-splitting )
