### ISSUE TITLE
useRequest组件卸载中发生错误

### ISSUE THREAD

**Issue by raohuiyong** [ice-lab/icejs#234]
描述：
当我使用useRequest请求接口的时候，接口由于响应比较慢（如需要5秒），在这个响应的过程中，如果切换路由，会发生一个警告的错误

错误日志
Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

``` javascript
import React, { useEffect, useState } from 'react';
import { useRequest, withRouter } from 'ice';
import axios from 'axios';

const Analysis = () => {
  const { data, loading = true, request } = useRequest({
    url: '/api/projects',
    method: 'GET',
  });
  const [source] = useState(axios.CancelToken.source());
  useEffect(() => {
    request({ data: { name: 'raohuiyong' }, cancelToken: source.token });
    return () => {
      source.cancel('组件卸载,取消请求');
    };
  }, []);
  return <div>测试请求</div>
  );
};
export default withRouter(Analysis);
```

![TIM截图20200410095727](https://user-images.githubusercontent.com/26049430/78955390-bcc66300-7b11-11ea-96a1-564dd3c48c83.png)

**Comment by raohuiyong** [comment]
``` javascript
// mock/index.js
module.exports = {
  'GET /api/projects': (req, res) => {
    setTimeout(() => {
      res.status(200).send({
        status: 'SUCCESS',
        data: projects,
      });
    }, 5000);
  },
};
```
1. 前提描述：
定义一个延迟5秒钟进行响应的mock，在5秒钟内进行组件的切换。

2. useRequest和request使用测试结果：
使用request数据请求方式，组件卸载后不会发生警告错误
使用useRequest数据请求方式，在组件卸载后会抛出一个警告异常

**Comment by chenbin92** [comment]
- 具体原因可参考：https://juejin.im/post/5bc7f852f265da0ac139488c
- 后续会通过 ahooks/useRequest 支持
