### ISSUE TITLE
窗口缩放页面接口重复请求问题

### ISSUE THREAD

**Issue by raohuiyong** [ice-lab/icejs#235]
我使用官网提供的Fusion Design Pro - TS项目进行测试，当我缩放窗口大小的时候，会重复请求当前接口的问题，[项目演示](https://codesandbox.io/s/github/raohuiyong/fallbackDemo)
![TIM截图20200410103141](https://user-images.githubusercontent.com/26049430/78956949-82ab9000-7b16-11ea-95ea-3f7d0b54c8db.png)

**Comment by raohuiyong** [comment]
测试发现，当窗口发生缩放后，整个route都会重新卸载并渲染

**Comment by chenbin92** [comment]
@raohuiyong   看下是不是 PRO 模板的响应式逻辑引起的

**Comment by imsobear** [comment]
@raohuiyong 有结论的话可以在 issue 里同步下

**Comment by raohuiyong** [comment]
发生原因：
我在LocaleProvider组件中动态修改了一个state的状态，并绑定到ConfigProvider组件的device属性，从而导致子路由重新绘制
结论：
在addProvider中任何状态的更新都会导致整个子路由的重绘
