### ISSUE TITLE
plugin-config 重构方案

### ISSUE THREAD

**Issue by ClarkXia** [ice-lab/icejs#24]
### 约定读取 configs/config.[j|t]s

config 定义如下：

```js
const config = {
  dev: {
    baseUrl: 'dev/',
  },
  prod: {
    baseUrl: 'prod/',    
  },
  default: {
    baseUrl: 'default/',
  }
};

export default config;
```

### plugin-config

1. 根据 --mode 注入响应的 APP_MODE
2. 在 `.ice` 目录下生成 config.ts，并导出 config，`import { config } from 'ice'`，config.ts 生成内容如下：

```js
import config from '@/configs/config';

const userConfig = {
  ...(config.default || {}),
  ...(config[process.env.APP_MODE] || {}),
};

export default userConfig;
```

由于 `createApp` 初始化前，工程层面已经完成 process.env.APP_MODE 注入和 config.ts 的生成，因此在不同地方 import 应该均可以拿到对应的配置信息

**Comment by imsobear** [comment]
看起来 OK，我之前想的有问题，这样实现好像更好一些

**Comment by chenbin92** [comment]
上面的方案没问题

关于 `configs/config.[j|t]s` 的文件命名需要确认下：

1. 看现在的模板应该是 `configs` =>  `config`
2. 现在只考虑 `config/config.js` 能从 `import { config } from 'ice'` 获取到，实际项目中应该还有其他的文件，这个是怎么考虑的？

之前的设想是类似下面这样:

```
src
├── config
│   ├── a.ts
│   ├── b.ts
│   ├── menuConfig.ts
│   └── index.ts  // 这个是入口文件，对等上面的 config.ts
```

```ts
// index.ts

import a from './a'
import b from './b'
import menuConfig from './menuConfig'

const config = {
  dev: {
      baseUrl: 'dev/',
   },
   prod: {
     baseUrl: 'prod/',    
   },
  default: {
    baseUrl: 'default/',
    // 如果需要导出其他内容可以在这里导出
    a,
    b,
    // 可选择性挂载 config 上
    // menuConfig
  }
}
```

**Comment by ClarkXia** [comment]
> 
> 1. 看现在的模板应该是 `configs` =>  `config`
> 2. 现在只考虑 `config/config.js` 能从 `import { config } from 'ice'` 获取到，实际项目中应该还有其他的文件，这个是怎么考虑的？
> 

1. 嗯 这个可以再确认下
2. menuConfig 这种一般不会因环境不同有所区分，不应该建议这样子去使用，感觉用 index 的话会给人导出目录下所有内容的感觉

**Comment by imsobear** [comment]
应该是一个文件就够了，其他文件就是正常的，写什么就是什么，我们只认 configs/config.ts 这个文件。

**Comment by chenbin92** [comment]
> menuConfig 这种一般不会因环境不同有所区分，不应该建议这样子去使用，感觉用 index 的话会给人导出目录下所有内容的感觉

@ClarkXia  menuConfig 只是举例，因为既然在 config 目录下就需要考虑其他 config 下的文件，只是想到这个问题提出来。如果我们只认 config/config.ts 约定好就行，其他没问题了。

然后在项目中可能的两种写法：

```ts
import { config } from 'ice'
import {  menuConfig, a, b } from '@src/config'
```

**Comment by chenbin92** [comment]
@ClarkXia 想了下如果 icejs 只认 `config/config.ts` 也没问题，如果有必要，用户可以把其他文件的内容导入到 config.ts 中去。稍微有点别扭
