### ISSUE TITLE
请问 "serverless" 和 "埋点统计" 两个 特性什么时候提供呢？

### ISSUE THREAD

**Issue by xianjun-li** [ice-lab/icejs#242]
关于埋点统计，我的需求是：统计菜单点击数、page打开次数。

**Comment by chenbin92** [comment]
@lewis-li  

1. Serverless 前后端一体化模式目前仅支持阿里内部开发者，面向社区的方案还在建设中，暂时无法给出具体时间。
2. 关于 「埋点统计」目前也是基于内部的埋点平台实现的不会对外。社区方案这块需要看下社区相应的实现，不知道有没有好的推荐，可以一起讨论下。

另外建议单独重新开一个「埋点统计」的 issue，不要把两件事放在一个 issue。这个先关闭了。
