### ISSUE TITLE
MPA 场景下缺少 models 注册机制

### ISSUE THREAD

**Issue by ClarkXia** [ice-lab/icejs#263]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

MPA  目前会在 app.js 中定义路由，页面下定义的 models 无法使用

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* icejs version：1.1.8
* Node verson：
* Platform：
* `build.json`：
* `src/app.(ts|js)`：

**What is the expected behavior?**

需要提供 MPA 下使用 page 级别 models 的实践

**Comment by chenbin92** [comment]
## 方案一

MPA 相比 SPA 由于目录组织方式不一致，使用方式目前也存在一定差异，如路由（包括配置/约定）逻辑失效。**考虑对 store 不进行 Provider 的自动注册，由用户自行注册 Provider。**

```diff
  ├── src/pages
  │    ├── Dashboard/
  │    │   ├── models/        # 状态管理
+ │    │   ├── store.js
  │    │   ├── app.js
  │    │   └── index.jsx
  │    └──  Home/
  │         ├── models/
+ │         ├── store.js
  │         ├── app.js
  │         └── index.jsx
```
* 优点：MPA 下 store 逻辑对用户完全透明，遵循 icestore 规范即可
* 缺点：MPA 与 SPA 使用方式不一致，需要用户自行注册 store 逻辑。

## 方案二

每个页面下新增 `routes.ts` 目录，与 SPA 下保持一致，通过 AST 解析将页面路径指向 `.ice` 目录下。

```diff
├── src/ 
  │   ├── layouts/
  │   └── pages/ 
  │        ├── Dashboard/ 
  │        │     ├── app.js
+ │        │     ├── routes.js    # 路由配置入口
  │        │     └── index.jsx 
```

* 优点：MPA 与 SPA 下使用 store 的方式保持一致，无需用户注册 Provider
* 缺点：需要额外增加 `routes.ts`  文件

**Comment by chenbin92** [comment]
结论：方案二。

**Comment by chenbin92** [comment]
已发布 icejs@1.2.0 版本支持
