### ISSUE TITLE
useRequest 支持传入 promise

### ISSUE THREAD

**Issue by imsobear** [ice-lab/icejs#264]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* icejs version：
* Node verson：
* Platform：
* `build.json`：
* `src/app.(ts|js)`：

**What is the expected behavior?**

```js
import { useRequest } from 'ice';
import service from '@/services/user';             // 应用级 service

export default function Todo() {
  // 无需传入参数
  const { data, error, loading, run } = useRequest(service.getRepos);
  // 动态传入参数
  const { data, error, loading, run } = useRequest(() => service.getRepos({ id: 1 }) );

  useEffect(() => {
    run();
  }, []);

  return (...);
}
```

**Comment by alvinhui** [comment]
关于动态参数应该是在 run 函数调用时传递，而不是声明 useRequest 时

```js
  const { data, error, loading, run } = useRequest(service.getRepos);

run({ id: 1 });
```

**Comment by imsobear** [comment]
## service 场景传参问题

这里需要明确下：方式 1 和方式 2 是否需要同时支持，还是说只支持方式 1。

可以先只支持方式 1，方式 2 有一些坑，比如 deps 写起来不直观。

```js
function Home() {
  // 已支持：独立使用 useRequest 支持参数合并
  const { data, error, loading, request } = useRequest({ url: '/api' });
  useEffect(() => {
    request({ data: {} });
  }, []);

  // service 方式 1：统一在 request() 时传递参数
  const { data, error, loading, request } = useRequest(service.getRepo);
  useEffect(() => {
    request({ query: {} });
  }, []);

  // service 方式 2：useRequest 和 request 都支持传递参数
  const { data, error, loading, request } = useRequest(() => service.getRepo({ index: 1 }));
  useEffect(() => {
    request({ query: {} });
  }, []);
}
```

## 类型问题

service 的场景调用 request 参数类型是 service 自定义的而不是 `AxiosRequestConfig` 了，这里是不是需要推导下参数类型？

**Comment by chenbin92** [comment]
## 问题

1. request 返回 axios response
2. useRequest 支持 Promise 返回 data（现在返回为 data.data = null）
3. 类型问题(参数类型，返回值类型)


```ts
async function getRepo(id: string) {
  return await request({
    url: '/repo',
    params: id
  });
}

// 返回值问题
// async function getRepo1() {
//   const data = await request({
//     url: '/repo'
//   });
//   data.message = data.status === 1 ? 'ok' : 'error';
//   return data;
// }

const Home = () => {
  const { data, loading, request: fetchRepo } = useRequest(getRepo);
  // data 为 null 问题
  console.log(data);

  useEffect(() => {
    //  参数类型问题
    fetchRepo('111');
  }
}
```

**Comment by imsobear** [comment]
反复想了下，无论是这个需求还是 faas 一体化那个需求，不应该通过 `useRequest` 来实现，这类需求本质上跟 request 是解耦的，应该通过类似 [useAsyncFn](https://streamich.github.io/react-use/?path=/story/side-effects-useasyncfn--docs) 这个 API 来实现。理论上直接用这个 API 是跑的通的，可以抽空试一下。

**Comment by chenbin92** [comment]
> 反复想了下，无论是这个需求还是 faas 一体化那个需求，不应该通过 `useRequest` 来实现，这类需求本质上跟 request 是解耦的，应该通过类似 [useAsyncFn](https://streamich.github.io/react-use/?path=/story/side-effects-useasyncfn--docs) 这个 API 来实现。理论上直接用这个 API 是跑的通的，可以抽空试一下。

使用 useAsyncFn 是可以支持 Service 需求的，示例如下：

**简单场景：**

1. 定义 Service
```ts
// service.ts
export default {
  async function getUser(id) {
    console.log(id);
    return await request({
      url: '/user',
      params: id
    });
  }
}
```

2. 请求数据
```ts
import service from '@/service';
export default = () => {
  // 传入 getUser Service
  const [state, fetch] = useAsyncFn(service.getUser)
  
  useEffect(() => {
    // 主动调用并传入参数 id = 1
    fetch(1)
  }, [fetch])
}
```

**复杂场景：**

1. 定义 Service 同上
2. 请求数据

```ts
import service from '@/service';
export default = () => {
  // 传入 getUser Service
  // 也可以在调用 useAsyncFn 时传参：const [stata, fetch] = useAsyncFn(() => service.getUser(id))
  const [state, fetch] = useAsyncFn(service.getUser)
  
  useEffect(() => {
    // 首次或者当依赖项 id 发生变化的时候会进行调用
    return id ? fetch(id) : null

    // 指定依赖
  }, [fetch, id])
}
```


说明：可以基于 useAsyncFn 将返回值改为与 useRequest 保持一致：

```ts
const [state, fetch] = useAsyncFn(fn, deps?: any[]);
=>
const { data, loading, error, request } = useAsync(fn, deps?: any[]);
```

---

> 这类需求本质上跟 request 是解耦的

这个需要讨论下，是否有必要单独提供 useAsyncFn 方式：

### 方案一

useRequest 兼容多种形式。

**API：**

```ts
const { data, loading, error, request } = useRequest(
  service: object | ((...args:any) => | object),
)
```

**示例：**

```ts
// 方式一：参数为配置对象（已支持）
const { data, loading, error, request }  = useRequest({ url: '/api/user' });

// 方式二：参数为 Promise （未支持）
const { data, loading, error, request } = useRequest(service.getUser)
```

**缺点：**
  * 参数形式不一致

**优点：**
  * 统一使用方式，在现有 useRequest 基础上扩展，无需提供额外的 API
  * 未来迁移到 [ahooks/useRequest](https://github.com/ice-lab/ahooks/issues/5) 更友好

### 方案二

提供 useAsyncFn 方式支持 Service。

```ts
import service from '@/service';
import { useAsyncFn } from 'ice';

export default () => {
  const { data, loading, error, request } = useAsyncFn(service.getUser);
}
```

**缺点：**
  * 在 useRequest 的基础上再导出 useAsyncFn，会导致两个 API 界限不清且容易混淆，可能存在既有 useRequest 的代码又有 useAsyncFn 的代码（在 Service 的场景下，useRequest 不应该被使用）

**优点：**
  * 职责明确，useAsyncFn 不关心具体的请求库，只接收 Service 即可
  * 严格按照 「定义 service」 -> 「useAsyncFn」 的流程，使用起来容易理解

综上：由于方案一只需要在现有的基础上支持 Promise 的写法，且只需要提供一个 useRequest API 即可，对用户的理解成本较低，个人建议方案一。

**Comment by chenbin92** [comment]
详见 PR：https://github.com/ice-lab/icejs/pull/301
