### ISSUE TITLE
pages 目录下存在 index 文件夹时页面加载报错

### ISSUE THREAD

**Issue by ClarkXia** [ice-lab/icejs#296]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

src 下目录结构：

```
|- pages
|    |- index
|    |    |- index.ts
|    |    |- index.scss
```

routes.ts 文件中引入方式如下：

```js
import Index from './pages/index'

...
```

访问 Index 组件对应页面的路由时，页面报错

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* icejs version：1.2.1
* Node verson：
* Platform：
* `build.json`：
* `src/app.(ts|js)`：

**What is the expected behavior?**

看是否可以兼容这种 case

**Comment by chenbin92** [comment]
已修复
