### ISSUE TITLE
--mode 支持区分工程配置

### ISSUE THREAD

**Issue by imsobear** [ice-lab/icejs#33]
类似之前的 build-plugin-env-config

**Comment by imsobear** [comment]
## 方案梳理：

跟[运行时配置](https://ice.work/docs/guide/basic/config#%E8%AE%BE%E7%BD%AE%E7%8E%AF%E5%A2%83)一样通过 `--mode` 区分环境，然后在 `build.json` 里即可根据环境配置，这一块直接做在 plugin-react-app 上即可：

```json
{
  "mode_start": {
     "define": {},
     "alias": {},
   },
  "mode_build": {
     "define": {},
     "alias": {},
   }
}
```

看下使用 mode_xxx 的命名还是再嵌套一层比如 mode.start、mode.build。

**Comment by ClarkXia** [comment]
不建议在顶层铺开不可枚举的配置项,

环境区分的配置可以统一收敛在 `modeConfig` 中
```json
{
  "modeConfig": {
    "start": {},
    "build": {}
  }
}
```
