### ISSUE TITLE
plugin-react-app 配置能力增强

### ISSUE THREAD

**Issue by imsobear** [ice-lab/icejs#42]
@ClarkXia 再梳理下这块

![image](https://user-images.githubusercontent.com/2505411/75003717-bd446500-54a3-11ea-8618-08061c29e6b3.png)

**Comment by imsobear** [comment]
没支持之前，需要通过下面的方式更改。

新建本地插件文件：

```bash
$ touch build.plugin.js
```

在 build.json 中引入：

```json
{
  "plugins": [
    "./build.plugin.js"
  ]
}
```

编写插件逻辑：

```js
module.exports = ({ onGetWebpackConfig }) => {
  onGetWebpackConfig((config) => {
     // 清除 babel-loader 的 exclude，默认会忽略 node_modules 
    ['jsx', 'tsx'].forEach(rule => {
      config.module
        .rule(rule)
        .exclude.clear()
    });
  });
}
```

**Comment by ClarkXia** [comment]
计划支持：

- compileDependencies: 支持编译 node_modules 下的依赖
- bablePlugins: 支持追加 babel plugin
- bablePresets: 支持追加 babel presets，通过参数支持覆盖和顺序指定
- cssLoaderOptions：css-loader 相关配置，浅合并
- sassLoaderOptions：sass-loader 相关配置，浅合并
- lessLoaderOptions：less-loader 相关配置，浅合并
- postcssrc：支持加载 postcss 配置文件
- terserOptions：压缩相关配置，浅合并

sourcemap 和 ignoreHtmlTemplate 已支持

**Comment by imsobear** [comment]
我们支持 babel.config.js 吗？

**Comment by ClarkXia** [comment]
> 我们支持 babel.config.js 吗？

没有开启 `babelrc` 的配置，大部分配置预置的情况下，支持这种方式会比较凌乱，类似 webpackrc

**Comment by imsobear** [comment]
嗯嗯，不一定要支持，我只是印象里记得有个项目里这么做过，所以要确认下。

另外，我记得之前还支持过自定义 postcss.config.js，这个也确认下。

**Comment by ClarkXia** [comment]
postcss.config.js 需要主动开启，开启后内置配置会清空，由 postcss 去自动加载相关配置文件
