### ISSUE TITLE
官方模板内置 icejs 的一些方案

### ISSUE THREAD

**Issue by imsobear** [ice-lab/icejs#50]
## 问题描述

官方模板目前主要是偏 UI 的，例如 store/config/request 这些都没有使用，建议内置。

**Comment by chenbin92** [comment]
应该是加一些实际的示例？

**Comment by imsobear** [comment]
恩 差不多一个意思~

**Comment by chenbin92** [comment]
@imsobear 这个 @ClarkXia  跟进下 ？

**Comment by ClarkXia** [comment]
see: https://github.com/alibaba-fusion/materials/pull/13
