### ISSUE TITLE
[教程]结合实际 case 增加一些示例

### ISSUE THREAD

**Issue by imsobear** [ice-lab/icejs#57]
需要考虑下以哪种方式承载透出，目前区块没有这样的能力

**Comment by chenbin92** [comment]
## 可参考的

- 类似 nuxt.js 以 [examples](https://nuxtjs.org/examples) 的方式，目前 icejs 已有 8 个项目示例，可以嵌套 codesanbox 到官网
- 类似 next.js 以 [教程](https://nextjs.org/learn/basics/using-shared-components) 的方式，经典的是以完成一个 [blog](https://guides.rubyonrails.org/getting_started.html) 为示例进行串联
