### ISSUE TITLE
Lazy Component 获取不到组件静态属性

### ISSUE THREAD

**Issue by chenbin92** [ice-lab/icejs#64]
## 问题描述

1. 路由定义
```ts
import { lazy } from 'react'

const PageA = lazy(() => import('./page/A'))
const PageB = lazy(() => import('./page/B'))

const routerConfig = [
   {
      path: '/a',
      component: PageA
  },
 {
      path: '/b',
      component: PageB
  },
]
```

2. 调用 wrapperRouteComponent 包装 PageComponent 时**无法获取组件的静态属性**

```ts
wrapperRouteComponent(wrapperPage)

export function wrapperPage(PageComponent) {

  // 获取不到 pageConfig
  const { pageConfig } = PageComponent;
  const { title, scrollToTop } = pageConfig || {};
  // ...
}
```

## 问题分析

将组件 lazy 之后，lazy 将传入的参数封装成一个 LazyComponent，大致实现如下：

```ts
export type LazyComponent<T> = {
  $$typeof: Symbol | number, 
  _ctor: () => Thenable<{default: T, ...}, mixed>,  // 对应组件的文件资源
  _status: 0 | 1 | 2,  // dynamic import 的状态
  _result: any,  // 加载之后返回组件的文件资源
  ...
};

// lazy component 实现 https://github.com/facebook/react/blob/e706721490e50d0bd6af2cd933dbf857fd8b61ed/packages/shared/ReactLazyComponent.js#L42

// 大致代码如下
function readLazyComponentType(lazyComponent) {
  const status = lazyComponent._status;
  const result = lazyComponent._result;
  switch (status) {
    case Resolved: {   // Resolve 时，呈现相应资源
      const Component = result;
      return Component;
    }
    case Rejected: { // Rejected 时，throw 相应 error
      const error = result;
      throw error;
    }
    case Pending: {  //  Pending 时, throw 相应 thenable
      const thenable = result;
      throw thenable;
    }
    default: { // 第一次执行走这里
      lazyComponent._status = Pending;
      const ctor = lazyComponent._ctor;
      const thenable = ctor();  //  Promise 机制
      thenable.then(moduleObject => {  // ... })
  }
}
```

如上，dynamic import 本身类似 Promise 的执行机制, 也具有 Pending、Resolved、Rejected 三种状态，lazy Component 结构如下

![image](https://user-images.githubusercontent.com/3995814/75405346-68439b80-5948-11ea-9fca-38ec4e5a8fd3.png)

lazy 执行完成之后可得到完整的组件信息

![image](https://user-images.githubusercontent.com/3995814/75405414-9b862a80-5948-11ea-9780-072f72b47021.png)

## 解决方案

```ts
import { lazy } from 'react'

const PageA = lazy(() => import('./page/A'))
const PageB = lazy(() => import('./page/B'))

// 约定式和配置式路由在 lazy 的场景下都需要工程处理
// 会打包两份？
import _PageA from './page/A'
import _PageB from './page/B'

const routerConfig = [
   {
      path: '/a',
      component: PageA,
       // 扩展字段
       static: { pageConifg: _pageA.pageConfig, name: _PageA.name }
  },
 {
      path: '/b',
      component: PageB,
      // 扩展字段
     static: { pageConifg: _pageA.pageConfig, name: _PageA.name }
  },
]
```

**Comment by ClarkXia** [comment]
### 解决方案

routes.ts 中加载方式修复为：

```js
const Page = import(/* webpackChunkName: 'Page' */ '../src/pages/index.tsx'));

export default [
...
{
     path: '/',
    exact: true,
    component: Page
}
...
]
```

在 Router 组件内部，如果传入 component 是一个 Promise，则构造 Lazy 及处理 wrapperRoute

```js
const RouteComponet = isPromis(component) ? lazy(() => component.then((module) => {
  module.default = wrapperRoute(module.default);
  return module;
})) : wrapperRoute(component);
```

**Comment by chenbin92** [comment]
> ### 解决方案
> routes.ts 中加载方式修复为：
> 
> ```js
> const Page = import(/* webpackChunkName: 'Page' */ '../src/pages/index.tsx'));
> 
> export default [
> ...
> {
>      path: '/',
>     exact: true,
>     component: Page
> }
> ...
> ]
> ```
> 
> 在 Router 组件内部，如果传入 component 是一个 Promise，则构造 Lazy 及处理 wrapperRoute
> 
> ```js
> const RouteComponet = isPromis(component) ? lazy(() => component.then((module) => {
>   module.default = wrapperRoute(module.default);
>   return module;
> })) : wrapperRoute(component);
> ```

如果 `routes.ts` 中是下面这种做法，那在配置式路由下如果需要开启 lazy 应该也是约定用户要这么写了

```ts
const Page = import(/* webpackChunkName: 'Page' */ '../src/pages/index.tsx'));
```

这里的思路是将 lazy 分为了两步吗

1. 定义时通过上面的形式保证能拿到 Component 的静态属性
2. 然后在 Router 中进行判断是是 lazyComponent 在加上 lazy 的逻辑，进一步说就是等 lazy 完之后返回的 module.default  进行 wrapper，但是这个时候 `lazy._status = 1`  React 组件已经渲染完了， 在包裹上去应该不会生效？如果生效逻辑我有点不理解

```ts
const RouteComponet = isPromis(component) ? lazy(() => component.then((module) => {
  module.default = wrapperRoute(module.default);
  return module;
})) : wrapperRoute(component);
```

**Comment by ClarkXia** [comment]
> 然后在 Router 中进行判断是是 lazyComponent 在加上 lazy 的逻辑，进一步说就是等 lazy 完之后返回的 module.default 进行 wrapper，但是这个时候 lazy._status = 1 React 组件已经渲染完了， 在包裹上去应该不会生效？如果生效逻辑我有点不理解

最终渲染时候拿个是 import 的 resolve，在这之前进行 wrapperRoute 肯定是可以生效的

**Comment by chenbin92** [comment]
https://github.com/ice-lab/icejs/pull/61
