### ISSUE TITLE
[RFC] 权限方案设计

### ISSUE THREAD

**Issue by imsobear** [ice-lab/icejs#70]
整体能力决定实现到 `plugin-ice-auth` 里，插件默认不内置。对比实现到 plugin-router 里：

优点：

- 不影响 bundle 大小
- 逻辑分离好维护

缺点：

- 多包一层 HOC

## 初始化用户角色

在 `src/app.ts` 中设置当前用户的角色：

```js
import { createApp, helpers, IAppConfig } from 'ice';
import NoAuthComponent from '@/components/NoAuthComponent';
const { cookie } = helpers;

const appConfig: IAppConfig = {
  app: {},
  auth: {
    setRole: () => {
      // 服务端将当前用户角色 role 保存在 cookie 中，或者通过全局变量等方式输出
      const { role } = cookie.parse(document.cookie);
      return role;
    },
    // 可选，配置无权限时的视图组件，默认有一个
    NoAuthComponent,
  }
};

createApp(appConfig);
```

### 异步获取角色

外部很多公司的 html 是托管在 nginx 这一层的，同步访问 html 时没有任何鉴权，鉴权/登录逻辑是在前端代码里调用的，通过 `app.getInitalData` 实现，`app.getInitalData` 有点像应用级别的支持同步/异步的 setup，可以考虑作为通用能力而不仅是服务于 SSR。大概的用法：

```js
import { createApp, helpers, IAppConfig } from 'ice';
import NoAuthComponent from '@/components/NoAuthComponent';
const { cookie } = helpers;

const appConfig: IAppConfig = {
  app: {
    getInitialData: async () => {
      const role = await request('/api/getRole');
      return { role };
    }
  },
  auth: {
    setRole: (initialData) => {
      return initialData.role;
    },
  }
};
```

## 页面/路由权限

通过 `pageConfig.roles` 声明当前页面允许哪些角色访问：

```js
import React from 'react';

const Home = () => {
  return <>Home Page</>;
};

Home.pageConfig = {
  // 允许的角色，若不配置则代表所有角色都可以访问
  roles: ['guest', 'admin'],

  // 对 roles 的补充，控制能力更强
  hasAuth: () => { return true; }
};

export default Home;
```

## 组件级权限

提供 `getRole()` API 获取当前用户的角色：

```js
import { getRole } from 'ice';

function CustomComponent() {
  const role = getRole();
  return (
    <>
        <div>当前用户角色：{role}</div>
        { role === 'admin' ? <span>确定</span> : null }
        { ['guest', 'admin' ].indexOf(role) !== -1 ? <span>更新</span> : <span>无权限</span> }
    </>
  );
}
```

## 菜单权限

业务代码结合 API `getRole()` 自己消化

## 操作权限抽象

> 不需要框架做什么事情，一个最佳实践

@TODO

## 相关链接

- 之前版本的权限方案：https://ice.work/docs/guide-0.x/dev/authority

**Comment by raohuiyong** [comment]
权限的问题大概什么什么能更新一个版本呀

**Comment by imsobear** [comment]
这周明确方案，下周发布 @raohuiyong

**Comment by imsobear** [comment]
@raohuiyong 更新了一版方案，可以一起看下哈，下周的版本会一起发布。

**Comment by boiawang** [comment]
```js
import React from 'react';
import { getRole, NoAuthComponent } from 'ice';

const Home = () => {
  const role = getRole();

  if (role !== 'admin') {
    return <NoAuthComponent />;
  }
  return (
    <div>
      <h2>Home Page</h2>
    </div>
  );
};

export default Home;
```

页面级可以考虑下这样？增加 pageConfig 对用户来说又会多一个成本，现在已经有 appConfig 了，appConfig/pageConfig 让我想起了小程序的设计。

除了权限，config 还可以配什么？

**Comment by boiawang** [comment]
讨论点：

1. plugin-ice-auth 是做什么的？没有 get 到点。
2. 是否需要这个？我觉得在某些非服务端托管的情况下 还是需要异步获取权限的。是不是可以考虑加 getRole/getRoleSync，但最好不要有阻塞吧？

**Comment by raohuiyong** [comment]
这种情况是初始化的时候就已经确认权限了。实际应用会有下面这种情况`（是我目前自己测试的方案）`：
当用户登录成功后，接口会返回一个菜单列表，包含所有页面相关的权限信息。目前通过测试修改了menuConfig.ts

实现效果：
- asideMenuConfig每一个页面通过自己的authorities属性配置权限列表，如增删改操作`(这个时候就需要在访问对应页面的时候获取到当前的权限信息)`
- asideMenuConfig每一个path地址需要和routerConfig中的路由path进行匹配，只有匹配上的才可以继续访问，如果没有匹配上会提示访问权限不足

``` javascript
const headerMenuConfig = [];

/** @description options
 * path {String} 路由地址
 * icon {String} 菜单的图标
 * name {String} 菜单的名称,
 * children {Array} 子菜单
 * hideInMenu {Boolean} 是否在菜单中显示
 * authorities {Array} 权限列表标识
 */
const asideMenuConfig = [
  {
    name: '首页',
    path: '/web',
    children: [
      {
        name: '数据页面',
        path: '/dashboard',
        icon: 'chart-pie',
        children: [
          {
            name: '分析页面',
            path: '/dashboard/analysis',
            authorities: ['add', 'edit']
          },
          {
            name: '监控页面',
            path: '/dashboard/Monitor',
            authorities: ['delete', 'add']
          }
        ]
      },
      {
        name: '列表页面',
        path: '/list',
        icon: 'chart-bar',
        children: [
          {
            name: '卡片列表',
            path: '/list/card'
          }
        ]
      }
    ]
  },
  {
    name: '系统配置',
    path: '/os',
    children: [
      {
        name: '结果&缺省',
        path: '/feedback',
        icon: 'warning',
        children: [
          {
            name: '成功页面',
            path: '/feedback/success'
          },
          {
            name: '失败页面',
            path: '/feedback/fail'
          }
        ]
      }
    ]
  }
];

export { headerMenuConfig, asideMenuConfig };

```

**Comment by imsobear** [comment]
@boiawang 

- pageConfig 目前有 title/scrollTop/spm(plugin-spm)/auth(plugin-auth) 这几个字段，放在这里面的话就需要 plugin-ice-auth 来实现这个逻辑，这样的好处是对业务逻辑没侵入
- 目前设计上来讲只有 `app.getInitialData` 是可阻塞式的获取一些应用级数据，如果 getInitialData 不阻塞（或者你支持异步的 getRole），会导致 App render 两次，这个不太符合预期

**Comment by boiawang** [comment]
@imsobear render 两次是对性能或者体验造成影响吗？

阻塞型的：一开始是白屏，等待 getInitialData 完成，渲染页面
非阻塞型：空数据渲染，这时候页面显示一般是没有权限，接着 getInitialData 接口请求完成渲染页面。

感觉后面的体验比前面的好吧？

**Comment by chenbin92** [comment]
> 1. 逻辑实现到哪里？
>建议直接放到 plugin-router 里

auth 是单独的配置字段，router 也有单独的配置字段，我建议还是分开实现比较合理，插件的职责明确，可维护性也好点。


> 通过 pageConfig.roles 声明当前页面允许哪些角色访问：
> ```ts
> Home.pageConfig = {
> // 允许的角色，若不配置则代表所有角色都可以访问
> roles: ['guest', 'admin']
> };```

这里的实现是需要在 wrapperRouteComponent 的时候获取 roles 去进行对比然后套一层 `NoAuthComponent` 组件 ？


>```ts
>const appConfig: IAppConfig = {
>  auth: {
>    getRole: () => {
>      // 服务端将当前用户角色 role 保存在 cookie 中，或者通过全局变量等方式输出
>      const { role } = cookie.parse(document.cookie);
>      return role;
>    },
>    // 配置无权限时的视图组件
>    NoAuthComponent,
>  }
>}; ```

字段确认：

* `appConfig.auth ` 确定
* `appConfig.auth.setRole` 确定 
* `pageConfig.roles` 确定（考虑未来添加 hasAuth 配置）
* `import { getRole } from 'ice'` 确定 

> 如何通过异步接口设置权限？

我理解通常的做法是空数据渲染一次，等数据回来再渲染一次。避免阻塞

> `import NoAuthComponent from '@/components/NoAuthComponent';`

这个是完全交给用户配置，还是默认可以内置一个组件。

**Comment by chenbin92** [comment]
已迁移至 https://github.com/alibaba/ice/issues/3169
