### ISSUE TITLE
使用页面状态提示找不到'ice/Home'这个模块

### ISSUE THREAD

**Issue by raohuiyong** [ice-lab/icejs#72]
按照[官网](https://ice.work/docs/guide/basic/store)提供的页面状态使用案例进行测试，项目运行时发生错误Module not found: Can't resolve 'ice/Home'
全局状态userState可以正常使用，页面状态pageState无法使用

``` javascript
import React from 'react';
import { store as appStore } from 'ice';
import { store as pageStore } from 'ice/Home';
import { ResponsiveGrid } from '@alifd/next';


const Analysis = () => {
  const [userState] = appStore.useModel('app');
  const [ pageState, pageAction ] = pageStore.useModel('default');
  console.log(userState);
  console.log(pageState);
  return (
    <ResponsiveGrid gap={20}>
    </ResponsiveGrid>
  );
};

export default Analysis;
```
Module not found: Can't resolve 'ice/Home'

**Comment by chenbin92** [comment]
参考示例项目：https://codesandbox.io/s/github/ice-lab/icejs/blob/master/examples/basic-store

另外贴一下你的目录结构看下

**Comment by raohuiyong** [comment]
> 参考示例项目：https://codesandbox.io/s/github/ice-lab/icejs/blob/master/examples/basic-store
> 
> 另外贴一下你的目录结构看下

理解错了，ice/Hone这个模块应该是对应src/pages/下面的文件地址
