### ISSUE TITLE
启动输出日志上报错误

### ISSUE THREAD

**Issue by chenbin92** [ice-lab/icejs#78]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

启动输出日志上报错误

* icejs version：
* Node verson：
* Platform：
* `build.json`：
* `src/app.(ts|js)`：

![image](https://user-images.githubusercontent.com/3995814/75838900-3b88fb80-5e02-11ea-8c99-f6afc6639444.png)

**What is the expected behavior?**

- 上报日志即便挂了也不要透出日志

**Comment by ClarkXia** [comment]
日志输入已优化（重新安装下依赖即可），也可以通过设置 DISABLE_COLLECT 环境变量的方式禁止上报
