### ISSUE TITLE
关于 `ice/pageName` 设计

### ISSUE THREAD

**Issue by chenbin92** [ice-lab/icejs#79]
## 现状

针对 store 的设计支持了通过 `ice/pageName` 的引用方式，如下：

```ts
import { store } from `ice/${pageName}`
```

## 问题

上述方案会引入一些问题：

1. 未支持 store 的按需加载

```ts
// .ice/pageStores.ts
//  导出所有页面定义的 store
import About from './pages/About/store';
import Home from './pages/Home/store';

const pageStores = { About,Home, };
export default pageStores;

// plugin-store/src/module.tsx
//  问题：一次性将所有 store 都进行导入，然后按照路由追加匹配的 Provider
// TODO：需要支持按需加载
import PageStores from '$ice/pageStores';
const wrapperComponent = (PageComponent) => {
  const { pageConfig = {} } = PageComponent;
  const StoreWrapperedComponent = (props) => {
    const pageComponentName = pageConfig.componentName;
    const PageStore = PageStores[pageComponentName];
    if (PageStore) {
      return (
        <PageStore.Provider initialState={pageConfig.initialStates}>
          <PageComponent {...props}/>
        </PageStore.Provider>
      );
    }
    return <PageComponent {...props} />;
  };
  return StoreWrapperedComponent;
};
```

2. 无法扩展出其他的二级引用引用，如 `import {  IAppConfig } from 'ice/types'`

```ts
// plugin-core/src/index.ts
onGetWebpackConfig((config: any) => {
    // 指定到 ./ice/index.ts
    config.resolve.alias.set('ice$', path.join(iceTempPath, 'index.ts'));
    // 问题：指定到 .ice/pages/* 下导致无法在扩展出其他二级路径，如 ice/types
    config.resolve.alias.set('ice', path.join(iceTempPath, 'pages'));
}
```

3. 通过页面名称作为 ice 的二级引用，对用户存在一些困扰，以及实现上不太优雅，最好是 all from ice （与 2 冲突？）

**Comment by imsobear** [comment]
all from ice 是一个追求的目标，这个目标本身是美好的，但要结合实际 case 具体来评估，比如页面级 store 这种情况，必须得通过变量名区分，那 all from ice 就变成了：

```js
import { store, homeStore, aboutStore } from 'ice';
```

这个是不是我们想要的？如果不是那可能是现在的 `ice/Home`，会导致扩展和 treeshaking 的问题，那是不是改成 `ice/pages/Home` ？

**Comment by alvinhui** [comment]
这样的一种声明对于组件级 model 如何支持也需要看一下。

例如，目录：

- src/pages/${pageName}/${componentName}/index.tsx
- src/layouts/${layoutName}/components/${componentName}/index.tsx
- src/components/${componentName}/index.tsx

在这些文件内，如何引用组件级的 Model ？

参考：

- 全局 store： `import { store } from 'ice'`
- 页面级 store： `import { store } from 'ice/${pageName}'`

**Comment by chenbin92** [comment]
**现状：**
- 全局 store： `import { store } from 'ice'`
- 页面级 store： `import { store } from 'ice/${pageName}'`
- 组件级 Model： `import { model } from 'ice/${pageName}/components/Todo'` https://github.com/ice-lab/icejs/issues/99#issuecomment-611352260

**问题：**
- 按需加载
- 其他二级路径扩展

**Comment by chenbin92** [comment]
## 提案

`import { request } from 'ice'; `
`import { store } from 'ice'`

改为 

`import request from 'ice/request'`
`import appStore from 'ice/appStore'`

**Comment by chenbin92** [comment]
## 结论

1. 二级扩展：ice/types 是个伪需求，社区一般做法通常不会单独从 ice/types 里导出 interface。暂无其他二级扩展
2. store 的按需加载：
   * 将挂载 Provider 逻辑放到 `.ice/${pageName}/index.ts 下`
   * 通过 AST 将用户引用的 `@/pages/${pageName}/` 改为 `ice/pages/${pageName}`

**Comment by chenbin92** [comment]
结论：
- store 按需加载问题已解决
- 暂无二级目录需求，维持现有设计
