### ISSUE TITLE
Support MPA

### ISSUE THREAD

**Issue by chenbin92** [ice-lab/icejs#8]
- plugin-mpa： 基于插件实现多页应用

**Comment by ClarkXia** [comment]
## plugin-mpa

方案设计原则：工程配置和 .ice 临时目录共用。

原则上共用工程配置，非动态生成的模块应该都可以共用，按目录结构生成，特别是 pages 纬度生成的逻辑需要特殊处理。

### 多 entry

默认 src/pages 下一级目录为一个 entry 入口

### 入口文件形式

同 spa 保持一致，默认以目录下的 `app.[t|j]s` 作为文件入口

#### 入口文件特殊逻辑

spa 场景下，appConfig 会直接通过 `createApp` 函数初始化项目，但是在 mpa 场景下很多情况需要特殊设置，比如 开启 mpa 下引用具体的 store，如果由开发这自己导入并指定成本会很高，建议在 app.[j|t]s 中仅导出 appConfig 配置，由自动生成的入口导入配置 appConfig，并根据配置和不同页面的 entry，完成一些自动注入和绑定的工作，具体绑定逻辑详见下文各部分功能方案

### 路由

目前不管是配置式路由还是约定是路由都会有 `$ice/routes` 的引入，在 mpa 的场景下同一工程路由的 alias 指向是唯一的，所以针对路由 module 的能力需要进行一定的改造

#### 方案一
mpa 场景下路由应该相对简单，可以直接禁用自动路由和约定路由的能力，通过 appConfig 中 `mpa` 的配置指定 render 到页面中的组件，比如

```js
import Dashboard from '.src/pages/Dashborad/index'; // 直接导入 mpa 页面的下 index 文件作为渲染内容
const appConfig = {
  mpa: {
     // renderComponent 作为 ReactDOM 渲染的初始节点
     renderComponent: Dashboard
  }
}
```

临时文件公用的情况下，需要通过 runtime 的配置，区分出渲染内容。

方案缺陷：store 这种在路由上增强的相关能力整体缺失。

#### 方案二
`$ice/routes` 默认指向导出空数组的文件，mpa 路由通过类似 `modifyRoutes` 能力添加上去，比如

```js
const appConfig = {
  router: {
    modifyRoutes: () => {
       // 按路由规则生成 routes 配置
       return [{ path: '/', component: Dashboard }]
    }
  }
}
```
可以通过约定方式自动追加。

基于 runtime 的 wrapperRouteComponent 和 router 的基本配置保证一定程度的可用

### 状态管理

#### store 插件

store 插件目前基于页面纬度进行绑定，通过路由设置方案二的形式可以完成绑定。

存在问题：pageModel 文件中引入了 所有 pages 目录纬度 model ，构建会存在冗余代码

#### rematch 插件

rematch 管理全局 store 文件，添加全局 provider 会存在和 store 插件同样问题

#### 方案一

mpa 场景下，运行时需要知道当前页面对应的 store 有哪些，需要提供手动指定的入口

```js
import pageModel from 'ice/pages/Dashborad/models'; 
// 按页面纬度加载对应的 models 并进行初始化绑定

const appConfig = {
  mpa: {
    store: pageModel
  }
}
```

#### 方案二

rematch 插件支持 mpa 模式，开启 mpa 后，以 src/pages 下一级目录的纬度去 init store
这块基于 mpa 的修改需要增加原插件的一些逻辑


### mpa 带来的问题

基于 spa 场景下开发的插件，特别是基于一定约定生成运行时代码的功能，在开启 mpa 后可能会出现一些异常情况

**Comment by chenbin92** [comment]
## 方案一

方案一导致 wrapperRoute 能力 、store 等插件不可用存在问题较多，不建议采纳

## 方案二

方案较为合理，但在 rematch 的场景下会有问题：

### 问题
由于 reactch 是通过全局 store 组织管理状态，在 mpa 的场景下会导致冗余代码的引用。

### 解决

建议是 mpa 的场景下，rematch 推荐按照页面 store 的维度划分，如下：

```md
- pages
   - home
         - store
   - about
        - store
```

这样的话，需要对 rematch 插件进行改造，判断是 mpa 的场景使用 page store 逻辑，判断是 spa 的场景使用 app store 的逻辑

**Comment by ClarkXia** [comment]
如果要对 appConfig 自动追加 mpa 下相关的约定配置，直接执行 createApp 还是有问题，原先的想法是：
```
生成临时entry -> 引入 appConfig -> 根据临时 entry 中生成的信息合并原 appConfig -> 执行 createApp
```

**Comment by chenbin92** [comment]
> 如果要对 appConfig 自动追加 mpa 下相关的约定配置，直接执行 createApp 还是有问题，原先的想法是：
> 
> ```
> 生成临时entry -> 引入 appConfig -> 根据临时 entry 中生成的信息合并原 appConfig -> 执行 createApp
> ```

问题是啥

**Comment by ClarkXia** [comment]
> 问题是啥

createApp 是统一从 ice 导出的，处理逻辑都是一致的，不管中间逻辑变更成什么，都无法针对每个 src/pages 下面的单独入口进行区分

**Comment by chenbin92** [comment]
> > 问题是啥
> 
> createApp 是统一从 ice 导出的，处理逻辑都是一致的，不管中间逻辑变更成什么，都无法针对每个 src/pages 下面的单独入口进行区分

理解了

**Comment by chenbin92** [comment]
## 小结

1. 每个 page 下面都有一个 `app.js` 文件，支持可能的差异化配置，如下：
    - rootId
    - routes

2.  `app.js` 内容如下：
```ts
import { createApp } from 'ice'
import routes from './routes'
const appConfig = {
  app: {
     rootId: '',
  },
  router: {
      modifyRoutes: () => routes
  }
}

createApp(appConfig)
```

**Comment by ClarkXia** [comment]
## MPA 使用

### 工程配置中增加 mpa 插件

```diff
{
  "plugins": [
    ...
+   "build-plugin-ice-mpa"
  ]
}
```

添加 mpa 插件后，默认将会以 `src/pages/ ` 下一级目录的每个 app.[t|j]s 作为应用入口

### 配置路由

开启 mpa 插件后，默认添加路由（包括配置/约定）的逻辑失效，需要手动配置 mpa 应用的路由
```diff
import { createApp } from 'ice';
+ import routes from './routes';

const appConfig = {
  app: {
    rootId: 'ice-container',
  },
+ router: {
+   modifyRoutes: () => routes
+ }
};
createApp(appConfig);
```

`routes` 文件中可以定义具体路由逻辑，一般 mpa 逻辑比较简单也可以直接进行配置：

```diff
import { createApp } from 'ice';
+ import Dashboard from './index';

const appConfig = {
  app: {
    rootId: 'ice-container',
  },
+ router: {
+   modifyRoutes: () => [{ path: '/', component: Dashboard }]
+ }
};
createApp(appConfig);
```

### 其他

* src/ 目录下 `app.[j|t]s` 和 `routes.js` 无效
* build-plugin-ice-rematch 暂时无法在 mpa 模式下使用
* plugin-store 能力使用保证同 spa 体验相同
