### ISSUE TITLE
启动服务构建 69% 卡主

### ISSUE THREAD

**Issue by chenbin92** [ice-lab/icejs#92]
## 问题

1. 执行 `icejs start` 一直卡在 69% 无法编译通过
2. 退出服务重新执行上一个端口被占用（没退出）

![demo](https://user-images.githubusercontent.com/3995814/76276581-24924f80-62c1-11ea-8a10-622759676c49.gif)

**Comment by ClarkXia** [comment]
有没有复现的 demo，另外卡在 69% 这个之前遇到过，大部分原因是项目构建量都很大

**Comment by chenbin92** [comment]
内部项目，发你钉钉了

**Comment by ClarkXia** [comment]
整体项目的 js 和 css 都达近 10M，在构建阶段会比较耗费时间，建议类似项目可以通过 `--analyzer` https://ice.work/docs/guide/basic/build#start 开启构建分析，移除不必要的依赖以及结合 externals 减少参与构建源码大小
