### ISSUE TITLE
IAppConfig 类型推导不正确

### ISSUE THREAD

**Issue by chenbin92** [ice-lab/icejs#93]
## 问题

如下图所示 IAppConfig 类型推导不正常：

![image](https://user-images.githubusercontent.com/3995814/76306860-9fc82580-6302-11ea-8c56-a45a5605d08d.png)

**Comment by imsobear** [comment]
appConfig 的类型在哪里定义的？插件可以动态修改吗？不能的话感觉这个问题不好解决？

**Comment by chenbin92** [comment]
插件可以动态修改 IAppConfig 和新增 types，提供了 addIceTypesExport 接口

```ts
applyMethod('addIceTypesExport', { source: './router/types', specifier: '{ IAppRouterProps }', exportName: 'router?: IAppRouterProps' });


```

**Comment by chenbin92** [comment]
上述图片的 ts 提示问题解释：
* 定义的 appconfig 变量是没声明类型的对象，没法推导，要写清楚类型（其实理想是可以自动推导appconfig，但是不支持）
* ts 对方法入参会做 duck type 校验，所以也可以通过直接传参即可

方式一：导入 IAppConfig  并改成 `const appConfig: IAppConfig = {}`
方式二：`createApp(配置直接写在这里)`

![image](https://user-images.githubusercontent.com/3995814/76378581-badd7880-6388-11ea-85c8-5b5fed2f6322.png)

**Comment by imsobear** [comment]
恩 方式一是合理的，ts 这块我们再统一验证下，没问题的话就统一改下模板

**Comment by chenbin92** [comment]
https://github.com/ice-lab/icejs/pull/102

**Comment by chenbin92** [comment]
已发布 icejs@1.0.15
