### ISSUE TITLE
MPA + fusion组合使用报错

### ISSUE THREAD

**Issue by FarmanYu** [ice-lab/icejs#97]
报个bug，MPA+ fusion组合使用， BasicLayout使用useModel，获取接口，编译正常，但浏览页面报如下错误:
```
createContainer.js:17 Uncaught Error: Component must be wrapped within a Provider.
    at createContainer.js:17
    at useModelState (createStore.js:38)
    at Object.useModel (createStore.js:49)
```

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* icejs version：1.0.14
* Node verson：10.8.0
* Platform：mac os
* `build.json`：
```json
{
  "outputDir": "dist",
  "devPublicPath": "/",
  "hash": true,
  "mpa": true,
  "publicPath": "/mini/admin/",
  "outputAssetsPath": {
    "js": "",
    "css": ""
  },
  "plugins": [
    [
      "build-plugin-fusion",
      {
        "themePackage": "@alifd/theme-design-pro"
      }
    ]
  ]
}
```
* `src/app.(ts|js)`：

页面在没有使用mpa方式时，可以正常浏览

**Comment by chenbin92** [comment]
@FarmanYu  写了个 demo 是支持的哈，对比检查下

mpa + layout + models 示例： https://codesandbox.io/s/mystifying-snow-1rzxn

![image](https://user-images.githubusercontent.com/3995814/76541732-f67a5e80-64be-11ea-85f1-bd48c29e5fed.png)
