### ISSUE TITLE
[RFC] [plugin-store] 提供组件级别的 Model 支持

### ISSUE THREAD

**Issue by alvinhui** [ice-lab/icejs#99]
## 需求背景

- 保持应用对状态管理处理方式的一致性（如果愿意整个应用都可以使用声明式模型来表达状态）；
- 互转模式下的 API 对齐。

### 目录结构

```bash
└── src/
    └── pages
        └── Home
            └── components
                └── Todos
                    ├── model.ts
                    └── index.ts
```

### 模型定义

```ts
// src/pages/Home/components/Todos/model.ts
export default {
  state: {
    name: '',
  },
  reducers: {
    setName: function(prevState, name) {
      return {
        ...prevState,
        name,
      };
    }
  }
}
```

### 模型消费

```jsx
// src/pages/Home/components/Todos/index.ts
import { model } from '$';
export default function() {
  const [state, actions] = model.useValue();

  return (
    <div>
      {state.name}
      <button onClick={() => {
        actions.setName('alvin');
      }}>click me</button>
    </div>
  );
}
```

**Comment by chenbin92** [comment]
> 保持应用对状态管理处理方式的一致性（如果愿意整个应用都可以使用声明式模型来表达状态）

1. 这和 `src/pages/*/models` 的设计是否存在冲突，什么时候应该放在 `src/pages/*/models`下，什么时候可以放在 `src/pages/*/component/model.ts` 里，两种的界限怎么定义的
2. 如果支持 `src/pages/*/component/model.ts` 这种方式，那整个应用的 Provider 是非常非常之多，可能会出现性能问题
3. 「如果愿意整个应用都可以使用声明式模型来表达状态」对于组件级别来说，组件的 Provider 上的数据只能供本组件以及子组件使用，我理解  `src/pages/*/component/model.ts` 组件多为单职责，很少会在嵌套其他的组件使用，如果会嵌套很多其他组件，那么这个组件的粒度和设计是否合理

> 互转模式下的 API 对齐

这个在互转模式下确定了吗？

**Comment by alvinhui** [comment]
1. 能够被复用的放到 `src/pages/*/models` ，不复用的组件本地状态放到 `src/pages/*/component/model.ts`
2. 组件的 model 在实现上不会有 provider(btw，provider 多应该不会有性能问题？)
3. 「如果愿意整个应用都可以使用声明式模型来表达状态」 这句话我想表达的是，理论上来说，开发者不需要在组件内 useState

**Comment by chenbin92** [comment]
> 能够被复用的放到 `src/pages/*/models `，不复用的组件本地状态放到 `src/pages/*/component/model.ts`

我的想法是：能力上可以支持，但源码链路不会推荐 component 带 model.ts，该场景适合 icejs+

**Comment by alvinhui** [comment]
> > 能够被复用的放到 `src/pages/*/models `，不复用的组件本地状态放到 `src/pages/*/component/model.ts`
> 
> 我的想法是：能力上可以支持，但源码链路不会推荐 component 带 model.ts，该场景适合 icejs+

是的。不会推荐，该场景仅适合 icejs+

**Comment by chenbin92** [comment]
## 实现

```ts
// pages/Home/components/Todo/view.tsx
// TODO: from '$';
import { model } from 'ice/Home/components/Todo';

// 调用 model 数据
console.log(model.useValue);
```

```ts
// pages/Home/components/Todo/store.ts
import store from '../../store'

export default {
  useValue() {
    return store.useModel('Todo')
  },
  useState() {
    return store.useModelState('Todo')
  },
  useDispatchers() {
    return store.useModelDispatchers('Todo')
  },
  getValue() {},
  getState() {},
  getDispatchers() {},
}
```

**Comment by alvinhui** [comment]
move to https://github.com/ice-lab/icejs/issues/244
